using DWIS.API.DTO;
using DWIS.RigOS.Common.Worker;
using DWIS.Vocabulary.Schemas;
using OSDC.DotnetLibraries.Drilling.DrillingProperties;
using OSDC.UnitConversion.Conversion;
using OSDC.UnitConversion.Conversion.DrillingEngineering;
using System.Reflection;

namespace DWIS.DAQBridge.UDPTopSideData.Model
{
    public class UDPTopSideData : DWISData
    {
        private static readonly Lazy<IReadOnlyDictionary<PropertyInfo, Dictionary<string, QuerySpecification>>> LocalSparQLQueries = new(BuildSparQLQueries(typeof(UDPTopSideData)));
        private static readonly Lazy<IReadOnlyDictionary<PropertyInfo, ManifestFile>> LocalManifests = new(BuildManifests(typeof(UDPTopSideData), "UDPTopSideDataManifest", "NORCE", "DWISBridge"));
        public override Lazy<IReadOnlyDictionary<PropertyInfo, Dictionary<string, QuerySpecification>>> SparQLQueries { get => LocalSparQLQueries; }
        public override Lazy<IReadOnlyDictionary<PropertyInfo, ManifestFile>> Manifests { get => LocalManifests; }

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BOS_depth")]
        [SemanticFact("BOS_depth", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BOS_depth#01", Nouns.Enum.Measurement)]
        [SemanticFact("BOS_depth#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BOS_depth#01", Verbs.Enum.HasDynamicValue, "BOS_depth")]
        [SemanticFact("BOS_depth#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.DepthDrilling)]
        [SemanticFact("movingAverageBOS_depth", Nouns.Enum.MovingAverage)]
        [SemanticFact("BOS_depth#01", Verbs.Enum.IsTransformationOutput, "movingAverageBOS_depth")]
        [SemanticFact("curvilinearAbscissaFrame#01", Nouns.Enum.OneDimensionalCurviLinearReferenceFrame)]
        [SemanticFact("BOS_depth#01", Verbs.Enum.HasReferenceFrame, "curvilinearAbscissaFrame#01")]
        [SemanticFact("bos#01", Nouns.Enum.BottomOfStringReferenceLocation)]
        [SemanticFact("BOS_depth#01", Verbs.Enum.IsPhysicallyLocatedAt, "bos#01")]
        [SemanticFact("BOS_depth#01", Nouns.Enum.BitDepth)]
        public ScalarProperty? BottomOfStringDepth { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("Q_tos")]
        [SemanticFact("Q_tos", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("Q_tos#01", Nouns.Enum.Measurement)]
        [SemanticFact("Q_tos#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("Q_tos#01", Verbs.Enum.HasDynamicValue, "Q_tos")]
        [SemanticFact("Q_tos#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.VolumetricFlowrateDrilling)]
        [SemanticFact("movingAverageQ_tos", Nouns.Enum.MovingAverage)]
        [SemanticFact("Q_tos#01", Verbs.Enum.IsTransformationOutput, "movingAverageQ_tos")]
        [SemanticFact("topOfStringJunction#01", Nouns.Enum.TopOfStringJunction)]
        [SemanticFact("inletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("topOfStringJunction#01", Verbs.Enum.HasUpstreamBranch, "inletHydraulicBranch#01")]
        [SemanticFact("Q_tos#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("Q_tos#01", Nouns.Enum.FlowRateIn)]
        public ScalarProperty? FlowrateIn { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("activeVolume")]
        [SemanticFact("activeVolume", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("activeVolume#01", Nouns.Enum.Measurement)]
        [SemanticFact("activeVolume#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("activeVolume#01", Verbs.Enum.HasDynamicValue, "activeVolume")]
        [SemanticFact("activeVolume#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.VolumeDrilling)]
        [SemanticFact("movingAverageactiveVolume", Nouns.Enum.MovingAverage)]
        [SemanticFact("activeVolume#01", Verbs.Enum.IsTransformationOutput, "movingAverageactiveVolume")]
        [SemanticFact("activePitLogical#01", Nouns.Enum.ActivePitLogical)]
        [SemanticFact("activeVolume#01", Verbs.Enum.IsVolumeAt, "activePitLogical#01")]
        public ScalarProperty? ActiveVolume { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("blockPosition")]
        [SemanticFact("blockPosition", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("blockPosition#01", Nouns.Enum.Measurement)]
        [SemanticFact("blockPosition#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("blockPosition#01", Verbs.Enum.HasDynamicValue, "blockPosition")]
        [SemanticFact("blockPosition#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.HeightDrilling)]
        [SemanticFact("movingAverageBlockPosition", Nouns.Enum.MovingAverage)]
        [SemanticFact("blockPosition#01", Verbs.Enum.IsTransformationOutput, "movingAverageBlockPosition")]
        [SemanticFact("elevator#01", Nouns.Enum.DrillPipeElevator)]
        [SemanticFact("blockPosition#01", Verbs.Enum.IsPhysicallyLocatedAt, "elevator#01")]
        [SemanticFact("blockPosition#01", Nouns.Enum.HookPosition)]
        public ScalarProperty? BlockPosition { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("SPP")]
        [SemanticFact("SPP", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("SPP#01", Nouns.Enum.Measurement)]
        [SemanticFact("SPP#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("SPP#01", Verbs.Enum.HasDynamicValue, "SPP")]
        [SemanticFact("SPP#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.PressureDrilling)]
        [SemanticFact("movingAverageSPP", Nouns.Enum.MovingAverage)]
        [SemanticFact("SPP#01", Verbs.Enum.IsTransformationOutput, "movingAverageSPP")]
        [SemanticFact("standPipe#01", Nouns.Enum.MudStandpipe)]
        [SemanticFact("SPP#01", Verbs.Enum.IsPhysicallyLocatedAt, "standPipe#01")]
        [SemanticFact("SPP#01", Nouns.Enum.SPP)]
        public ScalarProperty? StandPipePressure { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("ROP")]
        [SemanticFact("ROP", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("ROP#01", Nouns.Enum.Measurement)]
        [SemanticFact("ROP#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("ROP#01", Verbs.Enum.HasDynamicValue, "ROP")]
        [SemanticFact("ROP#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.RateOfPenetrationDrilling)]
        [SemanticFact("movingAverageROP", Nouns.Enum.MovingAverage)]
        [SemanticFact("ROP#01", Verbs.Enum.IsTransformationOutput, "movingAverageROP")]
        [SemanticFact("tos#01", Nouns.Enum.TopOfStringReferenceLocation)]
        [SemanticFact("ROP#01", Verbs.Enum.IsPhysicallyLocatedAt, "tos#01")]
        [SemanticFact("bh#01", Nouns.Enum.HoleBottomLocation)]
        [SemanticFact("ROP#01", Verbs.Enum.IsDependentOn, "bh#01")]
        [SemanticFact("ROP#01", Nouns.Enum.ROP)]
        public ScalarProperty? SurfaceRateOfPenetration { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("hookLoadAtAnchor")]
        [SemanticFact("hookLoadAtAnchor", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("hookLoadAtAnchor#01", Nouns.Enum.Measurement)]
        [SemanticFact("hookLoadAtAnchor#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("hookLoadAtAnchor#01", Verbs.Enum.HasDynamicValue, "hookLoadAtAnchor")]
        [SemanticFact("hookLoadAtAnchor#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.HookLoadDrilling)]
        [SemanticFact("movingAverageHookLoadAtAnchor", Nouns.Enum.MovingAverage)]
        [SemanticFact("hookLoadAtAnchor#01", Verbs.Enum.IsTransformationOutput, "movingAverageHookLoadAtAnchor")]
        [SemanticFact("deadLineAnchor#01", Nouns.Enum.DeadLineAnchor)]
        [SemanticFact("hookLoadAtAnchorAtTopDrive#01", Verbs.Enum.IsLocatedAtEquipment, "deadLineAnchor#01")]
        [SemanticFact("hook#01", Nouns.Enum.Hook)]
        [SemanticFact("hookLoadAtAnchor#01", Verbs.Enum.IsPhysicallyLocatedAt, "hook#01")]
        [SemanticFact("hookLoadAtAnchor#01", Nouns.Enum.HookLoad)]
        public ScalarProperty? HookLoadAtAnchor { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("hookLoadAtTopDrive")]
        [SemanticFact("hookLoadAtTopDrive", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("hookLoadAtTopDrive#01", Nouns.Enum.Measurement)]
        [SemanticFact("hookLoadAtTopDrive#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("hookLoadAtTopDrive#01", Verbs.Enum.HasDynamicValue, "hookLoadAtTopDrive")]
        [SemanticFact("hookLoadAtTopDrive#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.HookLoadDrilling)]
        [SemanticFact("movingAverageHookLoadAtTopDrive", Nouns.Enum.MovingAverage)]
        [SemanticFact("hookLoadAtTopDrive#01", Verbs.Enum.IsTransformationOutput, "movingAverageHookLoadAtTopDrive")]
        [SemanticFact("loadNut#01", Nouns.Enum.LoadNut)]
        [SemanticFact("hookLoadAtTopDrive#01", Verbs.Enum.IsLocatedAtEquipment, "loadNut#01")]
        [SemanticFact("hook#01", Nouns.Enum.Hook)]
        [SemanticFact("hookLoadAtTopDrive#01", Verbs.Enum.IsPhysicallyLocatedAt, "hook#01")]
        [SemanticFact("hookLoadAtTopDrive#01", Nouns.Enum.HookLoad)]
        public ScalarProperty? HookLoadAtTopDrive { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("surfaceTorque")]
        [SemanticFact("surfaceTorque", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("surfaceTorque#01", Nouns.Enum.Measurement)]
        [SemanticFact("surfaceTorque#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("surfaceTorque#01", Verbs.Enum.HasDynamicValue, "surfaceTorque")]
        [SemanticFact("surfaceTorque#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TorqueDrilling)]
        [SemanticFact("movingAverageSurfaceTorque", Nouns.Enum.MovingAverage)]
        [SemanticFact("surfaceTorque#01", Verbs.Enum.IsTransformationOutput, "movingAverageSurfaceTorque")]
        [SemanticFact("rotatingDriveSystem", Nouns.Enum.RotatingDriveSystemLocation)]
        [SemanticFact("surfaceTorque#01", Verbs.Enum.IsPhysicallyLocatedAt, "rotatingDriveSystem")]
        [SemanticFact("surfaceTorque#01", Nouns.Enum.SurfaceTorque)]
        public ScalarProperty? RotatingDriveSystemTorque { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("surfaceRotationalSpeed")]
        [SemanticFact("surfaceRotationalSpeed", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("surfaceRotationalSpeed#01", Nouns.Enum.Measurement)]
        [SemanticFact("surfaceRotationalSpeed#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("surfaceRotationalSpeed#01", Verbs.Enum.HasDynamicValue, "surfaceRotationalSpeed")]
        [SemanticFact("surfaceRotationalSpeed#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.AngularVelocityDrilling)]
        [SemanticFact("movingAverageSurfaceRotationalSpeed", Nouns.Enum.MovingAverage)]
        [SemanticFact("surfaceRotationalSpeed#01", Verbs.Enum.IsTransformationOutput, "movingAverageSurfaceRotationalSpeed")]
        [SemanticFact("rotatingDriveSystem", Nouns.Enum.RotatingDriveSystemLocation)]
        [SemanticFact("surfaceRotationalSpeed#01", Verbs.Enum.IsPhysicallyLocatedAt, "rotatingDriveSystem")]
        [SemanticFact("surfaceRotationalSpeed#01", Nouns.Enum.SurfaceRPM)]
        public ScalarProperty? RotatingDriveSystemRotationalSpeed { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("WOB")]
        [SemanticFact("WOB", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("WOB#01", Nouns.Enum.Measurement)]
        [SemanticFact("WOB#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("WOB#01", Verbs.Enum.HasDynamicValue, "WOB")]
        [SemanticFact("WOB#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.WeightOnBitDrilling)]
        [SemanticFact("movingAverageWOB", Nouns.Enum.MovingAverage)]
        [SemanticFact("WOB#01", Verbs.Enum.IsTransformationOutput, "movingAverageWOB")]
        [SemanticFact("tos#01", Nouns.Enum.TopOfStringReferenceLocation)]
        [SemanticFact("WOB#01", Verbs.Enum.IsPhysicallyLocatedAt, "tos#01")]
        [SemanticFact("bos#01", Nouns.Enum.BottomOfStringReferenceLocation)]
        [SemanticFact("bh#01", Nouns.Enum.HoleBottomLocation)]
        [SemanticFact("WOB#01", Verbs.Enum.IsDependentOn, "bos#01")]
        [SemanticFact("WOB#01", Verbs.Enum.IsDependentOn, "bh#01")]
        [SemanticFact("WOB#01", Nouns.Enum.WOB)]
        public ScalarProperty? SurfaceWeightOnBit { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("temperatureIn")]
        [SemanticFact("temperatureIn", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("temperatureIn#01", Nouns.Enum.Measurement)]
        [SemanticFact("temperatureIn#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("temperatureIn#01", Verbs.Enum.HasDynamicValue, "temperatureIn")]
        [SemanticFact("temperatureIn#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TemperatureDrilling)]
        [SemanticFact("movingAverageTemperatureIn", Nouns.Enum.MovingAverage)]
        [SemanticFact("temperatureIn#01", Verbs.Enum.IsTransformationOutput, "movingAverageTemperatureIn")]
        [SemanticFact("topOfStringJunction#01", Nouns.Enum.TopOfStringJunction)]
        [SemanticFact("inletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("topOfStringJunction#01", Verbs.Enum.HasUpstreamBranch, "inletHydraulicBranch#01")]
        [SemanticFact("temperatureIn#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("temperatureIn#01", Nouns.Enum.TemperatureIn)]
        public ScalarProperty? DrillingFluidTemperatureIn { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Assignable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("temperatureOut")]
        [SemanticFact("temperatureOut", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("temperatureOut#01", Nouns.Enum.Measurement)]
        [SemanticFact("temperatureOut#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("temperatureOut#01", Verbs.Enum.HasDynamicValue, "temperatureOut")]
        [SemanticFact("temperatureOut#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TemperatureDrilling)]
        [SemanticFact("movingAverageTemperatureOut", Nouns.Enum.MovingAverage)]
        [SemanticFact("temperatureOut#01", Verbs.Enum.IsTransformationOutput, "movingAverageTemperatureOut")]
        [SemanticFact("returnFlowLine#01", Nouns.Enum.ReturnFlowLine)]
        [SemanticFact("temperatureOut#01", Verbs.Enum.IsPhysicallyLocatedAt, "returnFlowLine#01")]
        [SemanticFact("annulusOutletJunction#01", Nouns.Enum.AnnulusOutletJunction)]
        [SemanticFact("outletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("annulusOutletJunction#01", Verbs.Enum.HasDownstreamBranch, "outletHydraulicBranch#01")]
        [SemanticFact("temperatureOut#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "outletHydraulicBranch#01")]
        [SemanticFact("temperatureOut#01", Nouns.Enum.TemperatureOut)]
        public ScalarProperty? DrillingFluidTemperatureOut { get; set; } = null;
    }
}
